import math

TITLE = "MAZE GAME"
RESOLUTION = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
FPS = 0

PLAYER_POSITIONS = 1.5, 1.5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.002
PLAYER_ROTATION = 0.002
PLAYER_SIZE = 60

MOUSE_SENS = 0.0002
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FOV = math.pi / 3
HALF_FOV = FOV / 2
RAYS_NUMBER = WIDTH // 2
HALF_RAYS_NUMER = RAYS_NUMBER // 2
DELTA_ANGLE = FOV / RAYS_NUMBER
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // RAYS_NUMBER

TEXTURE_SIZE = 512
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

MINIMAP_SCALE = 100

MAZE_SIZE = MAZE_WIDTH, MAZE_HEIGHT = 11, 11  # 51, 51